╒═══════════════════╤════════════════════╕
│ run config name   │                    │
╞═══════════════════╪════════════════════╡
│ CONFIG_NAME       │ dtsiamese_ssl_test │
├───────────────────┼────────────────────┤
│ device            │ cuda               │
├───────────────────┼────────────────────┤
│ epochs            │ 200                │
├───────────────────┼────────────────────┤
│ learning rate     │ 0.0001             │
├───────────────────┼────────────────────┤
│ batch size        │ 8                  │
╘═══════════════════╧════════════════════╛
['L15-0331E-1257N_1327_3160_13', 'L15-0361E-1300N_1446_2989_13', 'L15-0368E-1245N_1474_3210_13', 'L15-0387E-1276N_1549_3087_13', 'L15-0434E-1218N_1736_3318_13', 'L15-0544E-1228N_2176_3279_13', 'L15-0577E-1243N_2309_3217_13', 'L15-0586E-1127N_2345_3680_13', 'L15-0595E-1278N_2383_3079_13', 'L15-0614E-0946N_2459_4406_13', 'L15-0632E-0892N_2528_4620_13', 'L15-0683E-1006N_2732_4164_13', 'L15-0760E-0887N_3041_4643_13', 'L15-0977E-1187N_3911_3441_13', 'L15-1014E-1375N_4056_2688_13', 'L15-1015E-1062N_4061_3941_13', 'L15-1025E-1366N_4102_2726_13', 'L15-1138E-1216N_4553_3325_13', 'L15-1172E-1306N_4688_2967_13', 'L15-1185E-0935N_4742_4450_13', 'L15-1200E-0847N_4802_4803_13', 'L15-1204E-1202N_4816_3380_13', 'L15-1204E-1204N_4819_3372_13', 'L15-1289E-1169N_5156_3514_13', 'L15-1296E-1198N_5184_3399_13', 'L15-1335E-1166N_5342_3524_13', 'L15-1389E-1284N_5557_3054_13', 'L15-1438E-1134N_5753_3655_13', 'L15-1439E-1134N_5759_3655_13', 'L15-1481E-1119N_5927_3715_13', 'L15-1615E-1205N_6460_3370_13', 'L15-1615E-1206N_6460_3366_13', 'L15-1617E-1207N_6468_3360_13', 'L15-1669E-1153N_6678_3579_13', 'L15-1691E-1211N_6764_3347_13', 'L15-1709E-1112N_6838_3742_13', 'L15-1716E-1211N_6864_3345_13', 'L15-1748E-1247N_6993_3202_13', 'L15-1848E-0793N_7394_5018_13']
Dataset with 5900 samples.
Starting epoch 1/200.
Traceback (most recent call last):
  File "train_semisupervised_dualtask.py", line 193, in <module>
    run_training(cfg)
  File "train_semisupervised_dualtask.py", line 65, in run_training
    for i, batch in enumerate(dataloader):
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1373, in _process_data
    data.reraise()
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/antonimestre/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/antonimestre/Documents/Tesnime/SiameseSSL-master/utils/datasets.py", line 127, in __getitem__
    timestamps = self.metadata[aoi_id]
  File "<string>", line 2, in __getitem__
  File "/home/antonimestre/anaconda3/lib/python3.8/multiprocessing/managers.py", line 850, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'L15-1014E-1375N_4056_2688_13'