╒═══════════════════╤════════════════════╕
│ run config name   │                    │
╞═══════════════════╪════════════════════╡
│ CONFIG_NAME       │ dtsiamese_ssl_test │
├───────────────────┼────────────────────┤
│ device            │ cuda               │
├───────────────────┼────────────────────┤
│ epochs            │ 200                │
├───────────────────┼────────────────────┤
│ learning rate     │ 0.0001             │
├───────────────────┼────────────────────┤
│ batch size        │ 8                  │
╘═══════════════════╧════════════════════╛
Traceback (most recent call last):
  File "/home/antonimestre/Documents/Tesnime/SiameseSSL-master/train_semisupervised_dualtask.py", line 193, in <module>
    run_training(cfg)
  File "/home/antonimestre/Documents/Tesnime/SiameseSSL-master/train_semisupervised_dualtask.py", line 38, in run_training
    dataset = datasets.SpaceNet7CDDataset(cfg=cfg, run_type='training')
  File "/home/antonimestre/Documents/Tesnime/SiameseSSL-master/utils/datasets.py", line 90, in __init__
    self.metadata = geofiles.load_json(self.root_path / f'metadata_train.json')
  File "/home/antonimestre/Documents/Tesnime/SiameseSSL-master/utils/geofiles.py", line 104, in load_json
    with open(str(file)) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/antonimestre/Documents/Tesnime/SiameseSSL-master/SpaceNet7/metadata_train.json'